dist: trusty
language: node_js
node_js:
- '14'
cache:
  npm: false
services:
- docker
jobs:
  include:
    - stage: deploy
      if: branch = ci && tag IS blank
      before_install:
      - if [ -z ${GITHUB_TOKEN+x} ]; then travis_terminate 1; fi
      - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
      - git lfs pull
      - if [ -z ${NPM_TOKEN+x} ]; then travis_terminate 1; fi
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - if [ -z ${DOCKER_USERNAME+x} ]; then travis_terminate 1; fi
      - if [ -z ${DOCKER_PASSWORD+x} ]; then travis_terminate 1; fi
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export NPM_VERSION=$(node -e "console.log(require('./package.json').version)")
      - if [ -z ${NPM_VERSION} ]; then travis_terminate 1; fi
      install:
      - docker build . --tag guduf/trone:$NPM_VERSION || travis_terminate 1
      script:
      - docker run --rm guduf/trone:$NPM_VERSION pack start --dryRun
      - docker run --name troneci --entrypoint npm guduf/trone:$NPM_VERSION pack
      - docker cp troneci:/opt/trone/trone-$NPM_VERSION.tgz ./ || travis_terminate 1
      - git tag $NPM_VERSION || travis_terminate 1
      - npm publish ./trone-$NPM_VERSION.tgz
      - docker push guduf/trone:$NPM_VERSION
      - git push --tags
